# Generated by Django 4.0.6 on 2022-07-25 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTiControla',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('limiteMax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('limiteDisp', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
