# Generated by Django 4.0.6 on 2022-07-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTiControla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiticontrola',
            name='celular',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
