# Generated by Django 4.0.6 on 2022-07-12 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id_boleto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_boleto', models.CharField(max_length=255)),
                ('valor_boleto', models.CharField(max_length=255)),
            ],
        ),
    ]
