# Generated by Django 4.0.6 on 2022-07-12 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0003_alter_boleto_id_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='id_boleto',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
    ]
