# Generated by Django 4.0.6 on 2022-07-12 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0004_alter_boleto_id_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='valor_boleto',
            field=models.FloatField(blank='true', null='true'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='boleto',
            name='id_boleto',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
