# Generated by Django 4.0.6 on 2022-07-27 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id_card', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=255)),
                ('apelido', models.CharField(max_length=255)),
                ('data', models.DateField(default=0, max_length=12)),
                ('categoria', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
