version: '3'

services:
  api:
    container_name: api
    restart: always
    build: ./
    command: "./start.sh"
    ports:
      - "8080:8080"
    env_file:
      - ./debug.env
    # volumes:
    #   - .:/core
