# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Define o Kube config
        uses: Azure/k8s-set-context@v3.0
        with:
          # Acceptable values: kubeconfig (default) or service-account or service-principal
          method: kubeconfig
          # Contents of kubeconfig file
          kubeconfig: ${{secrets.K8S_CONFIG}}

      - name: Faz o deploy do cluster Kubernetes
        uses: Azure/k8s-deploy@v4.3
        with:
          images: |
            leommiranda/ti-controla-django-api:latest
          # Path to the manifest files which will be used for deployment.
          manifests: |
            ./k8s/deployment.yaml
          # # Resource group name - Only required if using private cluster
          # name: # optional
